sudo: false
language: go

services:
- redis-server

go:
- 1.9.x
- 1.10.x
- 1.11.x
- tip

matrix:
  allow_failures:
  - go: tip

install:
- go get github.com/go-redis/redis
- go get github.com/pkg/errors
